package entities;
// Generated Dec 6, 2016 12:08:45 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "dbleakfo_overtime")
public class Activity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer activityId;
	private String activityName;
	private Date activityDate;

	public Activity() {
	}

	public Activity(String activityName, Date activityDate) {
		this.activityName = activityName;
		this.activityDate = activityDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "activityID", unique = true, nullable = false)
	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	@Column(name = "activityName", nullable = false)
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activityDate", nullable = false, length = 10)
	public Date getActivityDate() {
		return this.activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

}
