package entities;
// Generated Dec 6, 2016 12:08:45 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeActivityId generated by hbm2java
 */
@Embeddable
public class EmployeeActivityId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int employeeId;
	private int activityId;

	public EmployeeActivityId() {
	}

	public EmployeeActivityId(int employeeId, int activityId) {
		this.employeeId = employeeId;
		this.activityId = activityId;
	}

	@Column(name = "employeeID", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "activityID", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeActivityId))
			return false;
		EmployeeActivityId castOther = (EmployeeActivityId) other;

		return (this.getEmployeeId() == castOther.getEmployeeId())
				&& (this.getActivityId() == castOther.getActivityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmployeeId();
		result = 37 * result + this.getActivityId();
		return result;
	}

}
