package entities;
// Generated Dec 6, 2016 12:08:45 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "dbleakfo_overtime")
public class Employee implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer employeeId;
	private String employeeName;
	private Date employeeHireDate;
	private int employeeSeniority;

	public Employee() {
	}

	public Employee(String employeeName, Date employeeHireDate, int employeeSeniority) {
		this.employeeName = employeeName;
		this.employeeHireDate = employeeHireDate;
		this.employeeSeniority = employeeSeniority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "employeeID", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "employeeName", nullable = false)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "employeeHireDate", nullable = false, length = 10)
	public Date getEmployeeHireDate() {
		return this.employeeHireDate;
	}

	public void setEmployeeHireDate(Date employeeHireDate) {
		this.employeeHireDate = employeeHireDate;
	}

	@Column(name = "employeeSeniority", nullable = false)
	public int getEmployeeSeniority() {
		return this.employeeSeniority;
	}

	public void setEmployeeSeniority(int employeeSeniority) {
		this.employeeSeniority = employeeSeniority;
	}

}
