package entities;
// Generated Dec 6, 2016 12:08:45 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeActivity generated by hbm2java
 */
@Entity
@Table(name = "employee_activity", catalog = "dbleakfo_overtime")
public class EmployeeActivity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private EmployeeActivityId id;
	private String employeeName;
	private String activityName;
	private Date activityDate;

	public EmployeeActivity() {
	}

	public EmployeeActivity(EmployeeActivityId id, String employeeName, String activityName, Date activityDate) {
		this.id = id;
		this.employeeName = employeeName;
		this.activityName = activityName;
		this.activityDate = activityDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeId", column = @Column(name = "employeeID", nullable = false)),
			@AttributeOverride(name = "activityId", column = @Column(name = "activityID", nullable = false)) })
	public EmployeeActivityId getId() {
		return this.id;
	}

	public void setId(EmployeeActivityId id) {
		this.id = id;
	}

	@Column(name = "employeeName", nullable = false)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "activityName", nullable = false)
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activityDate", nullable = false, length = 10)
	public Date getActivityDate() {
		return this.activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

}
